"""Mock feasibility analysis endpoint.

This simulates an "AI-powered" feasibility check with deterministic,
rule-based logic only. No external AI/ML service is called.
"""

import hashlib

from flask import Blueprint, current_app, jsonify

from app.auth import require_auth

feasibility_bp = Blueprint("feasibility", __name__, url_prefix="/api/enterprises")


def _deterministic_score(enterprise_id: str) -> int:
    """Turns the enterprise id into a stable pseudo-score between 40-95,
    so the same enterprise always gets the same demo result."""
    digest = hashlib.sha256(enterprise_id.encode("utf-8")).hexdigest()
    return 40 + (int(digest[:8], 16) % 56)


def _band(score: int) -> str:
    if score >= 75:
        return "high"
    if score >= 55:
        return "moderate"
    return "low"


@feasibility_bp.post("/<enterprise_id>/feasibility")
@require_auth
def feasibility_analysis(enterprise_id: str):
    enterprise = current_app.db.get_collection("enterprises").find_one(enterprise_id)
    if not enterprise:
        return jsonify({"error": "Enterprise not found"}), 404

    score = _deterministic_score(enterprise_id)
    band = _band(score)

    result = {
        "enterprise_id": enterprise_id,
        "viability_score": score,
        "market_reach": band,
        "competition": "low" if band == "high" else "moderate",
        "pricing_assessment": "reasonable" if band != "low" else "needs review",
        "strengths": ["Local demand identified", "Owner has relevant experience"],
        "weaknesses": ["Limited working capital", "No formal record-keeping yet"],
        "opportunities": ["Government scheme support available"],
        "risks": ["Seasonal demand fluctuation"],
        "recommendation": (
            "Proceed with additional working-capital planning"
            if band != "low"
            else "Reassess business plan before proceeding"
        ),
        "disclaimer": "MOCK/DEMO output generated by deterministic logic - not a real AI assessment.",
    }
    return jsonify(result), 200
